name: 'Pytest & Coverage Reporter'
description: 'Run tests and generate coverage summary'
inputs:
  pr-number:
    description: 'PR number'
    required: true
  work-dir:
    description: 'the root folder of the package'
    required: true
  package-name:
    description: 'test package name run'
    required: true
  coverage-threshold:
    description: 'Minimum coverage % to pass'
    required: false
    default: '70'
  workload_identity_provider:
    description: 'The workload identity provider'
    required: false
  service_account:
    description: 'The service account to use'
    required: false
runs:
  using: "composite"
  steps:
    - name: 'Authenticate to Google Cloud'
      if: ${{ inputs.workload_identity_provider != '' && inputs.service_account != '' }}
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}
        token_format: id_token
        id_token_audience: 'https://us-central1-etsy-xscitools-dev.cloudfunctions.net/enqueue_catapult_pdf_link'


    - name: Setup gcloud
      if: ${{ inputs.service_account != '' }}
      uses: google-github-actions/setup-gcloud@v2

    - name: Get identity token
      if: ${{ inputs.service_account != '' }}
      shell: bash
      run:
        gcloud artifacts packages list \
          --repository=experimentation-pypi \
          --location=us-central1 \
          --project=etsy-xscitools-dev
        echo "ID_TOKEN=${{ steps.auth.outputs.id_token }}" >> $GITHUB_ENV

    - name: Configure pip to use Artifact Registry
      if: ${{ inputs.service_account != '' }}
      shell: bash
      run: |
        gcloud artifacts print-settings python \
          --project=etsy-xscitools-dev \
          --repository=experimentation-pypi \
          --location=us-central1 >> ~/.pypirc

    - name: 'Run Tests and Generate Coverage'
      shell: bash
      run: |   
        chmod +x ${{ github.action_path }}/scripts/run.sh
        ${{ github.action_path }}/scripts/run.sh
      env:
        PR_NUMBER: ${{ inputs.pr-number }}
        WORK_DIR: ${{ inputs.work-dir }}
        PACKAGE_NAME: ${{ inputs.package-name }}
        TEST_FOLDER: ${{ inputs.test-folder }}
        COVERAGE_THRESHOLD: ${{ inputs.coverage-threshold }}
        WORKLOAD_IDENTITY_PROVIDER: ${{ inputs.workload_identity_provider }}
        SERVICE_ACCOUNT: ${{ inputs.service_account }}
      working-directory: ${{ inputs.work-dir }}

    - name: Find existing comment
      id: find-comment
      uses: peter-evans/find-comment@v3
      continue-on-error: true
      with:
        issue-number: ${{ inputs.pr-number }}
        comment-author: 'github-actions[bot]'
        body-includes: '<!-- pytest-report for ${{ inputs.package-name }} -->'

    - name: update PR comment
      if: ${{ steps.find-comment.outputs.comment-id != '' }}
      uses: peter-evans/create-or-update-comment@v4
      with:
        body-path: ${{ inputs.work-dir }}/summary.txt
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        edit-mode: replace
        reactions-edit-mode: replace

    - name: Create comment
      if: ${{ steps.find-comment.outputs.comment-id == '' }}
      uses: peter-evans/create-or-update-comment@v3
      with:
        body-path: ${{ inputs.work-dir }}/summary.txt
        issue-number: ${{ inputs.pr-number }}
        reactions: '+1'